new file:   bin/dosync 	modified:   install 	modified:   zsh/zsh.env

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,24 +2,29 @@
 # ============================================================================= #
 #  ➜ ➜ ➜ VARIABLES
 # ============================================================================= #
-DOSYNC_VERSION="0.1"
+DOSYNC_VERSION="v0.1"
 DOTFILES="$HOME/.dotfiles"
 SYNCFILE="$DOTFILES/sync.config"
 GITOPT="-q"
 GITSUB="--quiet"
 GITSUBOPT="--quiet"
 INSTALL_FONTS="${INSTALL_FONTS:-no}"
+INSTALL_DOSYNC="${INSTALL_DOSYNC:-no}"
 NO_TTY="${NOTTY:-no}"
 PIPED="${PIPED:-no}"
 
 # ============================================================================= #
 #  ➜ ➜ ➜ FUNCTIONS
 # ============================================================================= #
-#    export TERM="xterm-256color"
 
 ERROR() {
     echo "$@" >&2
     exit 1
+}
+
+FINISHED() {
+    echo "Finished successfully!"
+    exit 0
 }
 
 HAS_TERMINAL() {
@@ -42,24 +47,24 @@ IS_GIT() {
 }
 
 INIT_LOCAL() {
-    cd "$DOTFILES"
+    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
     IS_GIT
     # init the main repo
     git submodule $GITSUB update --init --recursive
-    cd
+    cd || return 0
 }
 
 GET_GIT_ORIGIN() {
-    cd "$DOTFILES"
+    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
     if [[ -d .git ]]; then
         ORIGIN=$(git config -l | grep remote.origin.url | awk -F'=' '{print $2}')
     fi
-    cd
+    cd || return 0
 }
 
 GIT_PULL() {
     GET_GIT_ORIGIN
-    cd "$DOTFILES"
+    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
     IS_GIT
     echo "Pulling latest changes from $ORIGIN"
     git pull $GITOPT
@@ -68,23 +73,23 @@ GIT_PULL() {
     git submodule $GITSUBOPT sync
     git submodule $GITSUBOPT foreach --recursive git fetch
     git submodule $GITSUBOPT update --init --recursive
-    cd
+    cd || return 0
 }
 
 GIT_COMMIT() {
     GET_GIT_ORIGIN
-    cd "$DOTFILES" || exit 1
+    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
     echo "Commiting latest changes to the repository"
     git commit -a $GITOPT
-    cd || return
+    cd || return 0
 }
 
 GIT_PUSH() {
     GET_GIT_ORIGIN
-    cd "$DOTFILES"
+    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
     echo "Pushing changes upstream to $ORIGIN" &&
         git push $GITOPT
-    cd
+    cd || return 0
 }
 
 GET_SYNCFILE() {
@@ -116,18 +121,24 @@ GET_FILE() {
     fi
     dotfile="$HOME/$dstfile"
 }
-OPTIONS_LIST() {
+GET_OPTIONS() {
     if [ "$NO_TTY" = yes ]; then
         echo "No tty"
+        FINISHED
     fi
-
     if [ "$INSTALL_FONTS" = yes ]; then
         echo "Installing fonts"
+        FINISHED
+    fi
+    if [ "$INSTALL_DOSYNC" = yes ]; then
+        echo "Installing DoSync as command"
+        ln -sf "$DOTFILES/install" "$DOTFILES/bin/dosync"
+        export PATH="$PATH:$DOTFILES/bin"
+        FINISHED
     fi
 }
 
 DO_OPTIONS() {
-    OPTIONS_LIST "$@"
     if HAS_TERMINAL; then
         export TERM="xterm-256color"
     fi
@@ -136,27 +147,29 @@ DO_OPTIONS() {
         NO_TTY=yes
     fi
     if IS_PIPED; then
-        PIPED=true
+        PIPED=yes
     fi
     while [ $# -gt 0 ]; do
         case $1 in
         --unattended) NO_TTY=yes ;;
+        --dosync) INSTALL_DOSYNC=yes ;;
         --fonts) INSTALL_FONTS=yes ;;
         -u | --pull)
             GIT_PULL
-            exit 0
+            FINISHED
             ;;
         -c | --commit)
             GIT_COMMIT
-            exit 0
+            FINISHED
             ;;
         -p | --push)
             GIT_PUSH
-            exit 0
+            FINISHED
             ;;
         esac
         shift
     done
+    GET_OPTIONS "$@"
 }
 
 DO_SYNC() {
@@ -167,7 +180,7 @@ DO_SYNC() {
         ln -sf "$dotsrc" "$dotfile"
         echo "Symlinked: $dotsrc -> $dotfile"
     done
-    exit 0
+    FINISHED
 }
 
 while true; do
